version: '3.8'

services:
  api:
    command: >
      sh -c "npm run start:prod"
    depends_on:
      - db
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/usersdb
      - DATABASE_SYNC=true
      - POKEMON_API_URL=https://pokeapi.co/api/v2
    restart: unless-stopped

  db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: usersdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
